apiVersion: v1
kind: ConfigMap
metadata:
  name: wcd-config
  namespace: wcd-platform
data:
  KAFKA_BOOTSTRAP_SERVERS: "wcd-redpanda:9092"
  REDIS_HOST: "wcd-redis-master"
  REDIS_PORT: "6379"
  WCD_API_KEY: "dev-secret-key"
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "wcd-redpanda:9092"
  SPRING_DATA_REDIS_HOST: "wcd-redis-master"
  SPRING_DATA_REDIS_PORT: "6379"