apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: wcd-production
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: wcd-system
spec:
  provider:
    gcpsm:
      projectID: wcd-platform-sem6
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-sm-credentials
            key: credentials.json
---
# Service Account for External Secrets Operator
# Must be annotated for Workload Identity
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: wcd-production
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: wcd-system
  annotations:
    # Link to GCP Service Account with Secret Manager access
    iam.gke.io/gcp-service-account: external-secrets@wcd-platform-sem6.iam.gserviceaccount.com
